In [50]:
import numpy 
import os
import urllib.request as req
from bs4 import BeautifulSoup
from nltk import word_tokenize
import nltk
import re #for reguler expression
#pip install BeautifulTable in anaconda cmd
from beautifultable import BeautifulTable
## for one-hot encoding
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from glob import glob
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [51]:
# pip3 install keras
#pip install tensorflow
#from keras.utils import to_categorical


In [52]:
url = "http://news.bbc.co.uk/2/hi/health/2284783.stm"
html = req.urlopen(url).read() #Much of the text on the web is in the form of HTML documents
#type(html)
print(html)#as we can see text was utf8 encoded

b'<!doctype html public "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">\r\n<html>\r\n<head>\r\n<title>BBC NEWS | Health | Blondes \'to die out in 200 years\'</title>\r\n<meta name="keywords" content="BBC, News, BBC News, news online, world, uk, international, foreign, british, online, service">\r\n<meta name="OriginalPublicationDate" content="2002/09/27 11:51:55">\r\n<meta name="UKFS_URL" content="/1/hi/health/2284783.stm">\r\n<meta name="IFS_URL" content="/2/hi/health/2284783.stm">\r\n<meta name="HTTP-EQUIV" content="text/html;charset=iso-8859-1">\r\n<meta name="Headline" content="Blondes \'to die out in 200 years\'">\r\n<meta name="Section" content="Health">\r\n<meta name="Description" content="Natural blondes are an endangered species and will die out by 2202, a study suggests.">\r\n<!-- GENMaps-->\r\n<map name="banner">\r\n<area alt="BBC NEWS" coords="7,9,167,32" href="http://news.bbc.co.uk/1/hi.html" shape="RECT">\r\n</map>\r\n\r\n<script src="

In [53]:
html = req.urlopen(url).read().decode('utf8') #convert to string
print(type(html))


<class 'str'>


## You can type print(html) to see the HTML content in all its glory, including meta tags, an image map, JavaScript, forms, and tables.

In [54]:
print(html[:60])
print(html)

<!doctype html public "-//W3C//DTD HTML 4.0 Transitional//EN
<!doctype html public "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html>
<head>
<title>BBC NEWS | Health | Blondes 'to die out in 200 years'</title>
<meta name="keywords" content="BBC, News, BBC News, news online, world, uk, international, foreign, british, online, service">
<meta name="OriginalPublicationDate" content="2002/09/27 11:51:55">
<meta name="UKFS_URL" content="/1/hi/health/2284783.stm">
<meta name="IFS_URL" content="/2/hi/health/2284783.stm">
<meta name="HTTP-EQUIV" content="text/html;charset=iso-8859-1">
<meta name="Headline" content="Blondes 'to die out in 200 years'">
<meta name="Section" content="Health">
<meta name="Description" content="Natural blondes are an endangered species and will die out by 2202, a study suggests.">
<!-- GENMaps-->
<map name="banner">
<area alt="BBC NEWS" coords="7,9,167,32" href="http://news.bbc.co.uk/1/hi.html" shape="RECT">
</map>

<script s

To get text out of HTML we will use a Python library called BeautifulSoup

In [55]:
raw = BeautifulSoup(html, 'html.parser').get_text()
print (raw)




BBC NEWS | Health | Blondes 'to die out in 200 years'






































NEWS
  SPORT
  WEATHER
  WORLD SERVICE

  A-Z INDEX 

  SEARCH 












































     You are in: Health  
    
    











News Front Page





Africa


Americas


Asia-Pacific


Europe


Middle East


South Asia


UK


Business


Entertainment


Science/Nature


Technology


Health


Medical notes


-------------


Talking Point


-------------


Country Profiles


In Depth


-------------


Programmes


-------------


























SERVICES







Daily E-mail







News Ticker







Mobile/PDAs






-------------















Text Only








Feedback







Help
























EDITIONS







Change to UK















Friday, 27 September, 2002, 11:51 GMT 12:51 UK

Blondes 'to die out in 200 years'


Scientists believe the last blondes will be in Finland



	The last natural blondes will die out within 200 years, scientists belie

In [56]:
tokens = word_tokenize(raw)
tokens

['BBC',
 'NEWS',
 '|',
 'Health',
 '|',
 'Blondes',
 "'to",
 'die',
 'out',
 'in',
 '200',
 "years'",
 'NEWS',
 'SPORT',
 'WEATHER',
 'WORLD',
 'SERVICE',
 'A-Z',
 'INDEX',
 'SEARCH',
 'You',
 'are',
 'in',
 ':',
 'Health',
 'News',
 'Front',
 'Page',
 'Africa',
 'Americas',
 'Asia-Pacific',
 'Europe',
 'Middle',
 'East',
 'South',
 'Asia',
 'UK',
 'Business',
 'Entertainment',
 'Science/Nature',
 'Technology',
 'Health',
 'Medical',
 'notes',
 '--',
 '--',
 '--',
 '--',
 '--',
 '--',
 '-',
 'Talking',
 'Point',
 '--',
 '--',
 '--',
 '--',
 '--',
 '--',
 '-',
 'Country',
 'Profiles',
 'In',
 'Depth',
 '--',
 '--',
 '--',
 '--',
 '--',
 '--',
 '-',
 'Programmes',
 '--',
 '--',
 '--',
 '--',
 '--',
 '--',
 '-',
 'SERVICES',
 'Daily',
 'E-mail',
 'News',
 'Ticker',
 'Mobile/PDAs',
 '--',
 '--',
 '--',
 '--',
 '--',
 '--',
 '-',
 'Text',
 'Only',
 'Feedback',
 'Help',
 'EDITIONS',
 'Change',
 'to',
 'UK',
 'Friday',
 ',',
 '27',
 'September',
 ',',
 '2002',
 ',',
 '11:51',
 'GMT',
 '12:51'

In [57]:
#tokens.index('Blondes') #gives the first index
indices_start = [i for i, x in enumerate(tokens) if x == "Blondes"] #gives lidt of indices
indices_end = [i for i, x in enumerate(tokens) if x == "disappear"] #gives lidt of indices
print(indices_end)
print(indices_start)
print(tokens[399])

[195, 355, 370, 400]
[5, 111]
n't


In [58]:
tokens_first_paragraph = tokens[111:402]
tokens_first_paragraph

['Blondes',
 "'to",
 'die',
 'out',
 'in',
 '200',
 "years'",
 'Scientists',
 'believe',
 'the',
 'last',
 'blondes',
 'will',
 'be',
 'in',
 'Finland',
 'The',
 'last',
 'natural',
 'blondes',
 'will',
 'die',
 'out',
 'within',
 '200',
 'years',
 ',',
 'scientists',
 'believe',
 '.',
 'A',
 'study',
 'by',
 'experts',
 'in',
 'Germany',
 'suggests',
 'people',
 'with',
 'blonde',
 'hair',
 'are',
 'an',
 'endangered',
 'species',
 'and',
 'will',
 'become',
 'extinct',
 'by',
 '2202',
 '.',
 'Researchers',
 'predict',
 'the',
 'last',
 'truly',
 'natural',
 'blonde',
 'will',
 'be',
 'born',
 'in',
 'Finland',
 '-',
 'the',
 'country',
 'with',
 'the',
 'highest',
 'proportion',
 'of',
 'blondes',
 '.',
 'The',
 'frequency',
 'of',
 'blondes',
 'may',
 'drop',
 'but',
 'they',
 'wo',
 "n't",
 'disappear',
 'Prof',
 'Jonathan',
 'Rees',
 ',',
 'University',
 'of',
 'Edinburgh',
 'But',
 'they',
 'say',
 'too',
 'few',
 'people',
 'now',
 'carry',
 'the',
 'gene',
 'for',
 'blondes',
 

In [59]:
porter = nltk.PorterStemmer()
lancaster = nltk.LancasterStemmer()
#print("Original : ",tokens_first_paragraph)


In [60]:
Porter_list=[porter.stem(t) for t in tokens_first_paragraph]
print("POrter stemmer result ",Porter_list)


POrter stemmer result  ['blond', "'to", 'die', 'out', 'in', '200', "years'", 'scientist', 'believ', 'the', 'last', 'blond', 'will', 'be', 'in', 'finland', 'the', 'last', 'natur', 'blond', 'will', 'die', 'out', 'within', '200', 'year', ',', 'scientist', 'believ', '.', 'A', 'studi', 'by', 'expert', 'in', 'germani', 'suggest', 'peopl', 'with', 'blond', 'hair', 'are', 'an', 'endang', 'speci', 'and', 'will', 'becom', 'extinct', 'by', '2202', '.', 'research', 'predict', 'the', 'last', 'truli', 'natur', 'blond', 'will', 'be', 'born', 'in', 'finland', '-', 'the', 'countri', 'with', 'the', 'highest', 'proport', 'of', 'blond', '.', 'the', 'frequenc', 'of', 'blond', 'may', 'drop', 'but', 'they', 'wo', "n't", 'disappear', 'prof', 'jonathan', 'ree', ',', 'univers', 'of', 'edinburgh', 'but', 'they', 'say', 'too', 'few', 'peopl', 'now', 'carri', 'the', 'gene', 'for', 'blond', 'to', 'last', 'beyond', 'the', 'next', 'two', 'centuri', '.', 'the', 'problem', 'is', 'that', 'blond', 'hair', 'is', 'caus', '

In [61]:
Lancaster_list=[lancaster.stem(t) for t in tokens_first_paragraph]
print("Lancaster stemmer result ", Lancaster_list)

Lancaster stemmer result  ['blond', "'to", 'die', 'out', 'in', '200', "years'", 'sci', 'believ', 'the', 'last', 'blond', 'wil', 'be', 'in', 'finland', 'the', 'last', 'nat', 'blond', 'wil', 'die', 'out', 'within', '200', 'year', ',', 'sci', 'believ', '.', 'a', 'study', 'by', 'expert', 'in', 'germany', 'suggest', 'peopl', 'with', 'blond', 'hair', 'ar', 'an', 'endang', 'specy', 'and', 'wil', 'becom', 'extinct', 'by', '2202', '.', 'research', 'predict', 'the', 'last', 'tru', 'nat', 'blond', 'wil', 'be', 'born', 'in', 'finland', '-', 'the', 'country', 'with', 'the', 'highest', 'proport', 'of', 'blond', '.', 'the', 'frequ', 'of', 'blond', 'may', 'drop', 'but', 'they', 'wo', "n't", 'disappear', 'prof', 'jonath', 'ree', ',', 'univers', 'of', 'edinburgh', 'but', 'they', 'say', 'too', 'few', 'peopl', 'now', 'carry', 'the', 'gen', 'for', 'blond', 'to', 'last', 'beyond', 'the', 'next', 'two', 'century', '.', 'the', 'problem', 'is', 'that', 'blond', 'hair', 'is', 'caus', 'by', 'a', 'recess', 'gen',

In [62]:
#Source: https://beautifultable.readthedocs.io/en/latest/quickstart.html
table = BeautifulTable()
table.columns.append(tokens_first_paragraph, header="Origin")
table.columns.append(Porter_list, header="Porter")
table.columns.append(Lancaster_list, header="Lancaster")

print(table)


+----------------+--------------+----------------+
|     Origin     |    Porter    |   Lancaster    |
+----------------+--------------+----------------+
|    Blondes     |    blond     |     blond      |
+----------------+--------------+----------------+
|      'to       |     'to      |      'to       |
+----------------+--------------+----------------+
|      die       |     die      |      die       |
+----------------+--------------+----------------+
|      out       |     out      |      out       |
+----------------+--------------+----------------+
|       in       |      in      |       in       |
+----------------+--------------+----------------+
|      200       |     200      |      200       |
+----------------+--------------+----------------+
|     years'     |    years'    |     years'     |
+----------------+--------------+----------------+
|   Scientists   |  scientist   |      sci       |
+----------------+--------------+----------------+
|    believe     |    believ   

## In this example, we will use the encoders from the scikit-learn library. Specifically, the LabelEncoder of creating an integer encoding of labels and the OneHotEncoder for creating a one hot encoding of integer encoded values.

In [63]:
values = array(tokens_first_paragraph)  
#values = array(['Blondes','to', 'die'])  # what will be the encoding in this case ?
print(values)


['Blondes' "'to" 'die' 'out' 'in' '200' "years'" 'Scientists' 'believe'
 'the' 'last' 'blondes' 'will' 'be' 'in' 'Finland' 'The' 'last' 'natural'
 'blondes' 'will' 'die' 'out' 'within' '200' 'years' ',' 'scientists'
 'believe' '.' 'A' 'study' 'by' 'experts' 'in' 'Germany' 'suggests'
 'people' 'with' 'blonde' 'hair' 'are' 'an' 'endangered' 'species' 'and'
 'will' 'become' 'extinct' 'by' '2202' '.' 'Researchers' 'predict' 'the'
 'last' 'truly' 'natural' 'blonde' 'will' 'be' 'born' 'in' 'Finland' '-'
 'the' 'country' 'with' 'the' 'highest' 'proportion' 'of' 'blondes' '.'
 'The' 'frequency' 'of' 'blondes' 'may' 'drop' 'but' 'they' 'wo' "n't"
 'disappear' 'Prof' 'Jonathan' 'Rees' ',' 'University' 'of' 'Edinburgh'
 'But' 'they' 'say' 'too' 'few' 'people' 'now' 'carry' 'the' 'gene' 'for'
 'blondes' 'to' 'last' 'beyond' 'the' 'next' 'two' 'centuries' '.' 'The'
 'problem' 'is' 'that' 'blonde' 'hair' 'is' 'caused' 'by' 'a' 'recessive'
 'gene' '.' 'In' 'order' 'for' 'a' 'child' 'to' 'have' 'blond

In [64]:
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(len(integer_encoded))


291


In [65]:
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
print(len(onehot_encoded))
print(len(onehot_encoded[0]))
#this means that there are some input words that weren't encoded..

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
291
150


What do you think the size of each vector is?

In [66]:
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[1, :])])
print(inverted)

["'to"]


In [67]:
onehot_encoded[0]
#complex representation

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## BOW

BOW using SKLEARN CountVectorizer.


In [68]:
import nltk
nltk.corpus.inaugural.fileids()

['1789-Washington.txt',
 '1793-Washington.txt',
 '1797-Adams.txt',
 '1801-Jefferson.txt',
 '1805-Jefferson.txt',
 '1809-Madison.txt',
 '1813-Madison.txt',
 '1817-Monroe.txt',
 '1821-Monroe.txt',
 '1825-Adams.txt',
 '1829-Jackson.txt',
 '1833-Jackson.txt',
 '1837-VanBuren.txt',
 '1841-Harrison.txt',
 '1845-Polk.txt',
 '1849-Taylor.txt',
 '1853-Pierce.txt',
 '1857-Buchanan.txt',
 '1861-Lincoln.txt',
 '1865-Lincoln.txt',
 '1869-Grant.txt',
 '1873-Grant.txt',
 '1877-Hayes.txt',
 '1881-Garfield.txt',
 '1885-Cleveland.txt',
 '1889-Harrison.txt',
 '1893-Cleveland.txt',
 '1897-McKinley.txt',
 '1901-McKinley.txt',
 '1905-Roosevelt.txt',
 '1909-Taft.txt',
 '1913-Wilson.txt',
 '1917-Wilson.txt',
 '1921-Harding.txt',
 '1925-Coolidge.txt',
 '1929-Hoover.txt',
 '1933-Roosevelt.txt',
 '1937-Roosevelt.txt',
 '1941-Roosevelt.txt',
 '1945-Roosevelt.txt',
 '1949-Truman.txt',
 '1953-Eisenhower.txt',
 '1957-Eisenhower.txt',
 '1961-Kennedy.txt',
 '1965-Johnson.txt',
 '1969-Nixon.txt',
 '1973-Nixon.txt',
 '1

In [69]:
path = nltk.data.find('corpora\inaugural/1805-Jefferson.txt')
path

FileSystemPathPointer('C:\\Users\\Lamia\\AppData\\Roaming\\nltk_data\\corpora\\inaugural\\1805-Jefferson.txt')

In [70]:
f = open(path)
raw = f.read()
print(raw)
print(len(raw))

Proceeding, fellow citizens, to that qualification which the Constitution requires before my entrance on the charge again conferred on me, it is my duty to express the deep sense I entertain of this new proof of confidence from my fellow citizens at large, and the zeal with which it inspires me so to conduct myself as may best satisfy their just expectations.

On taking this station on a former occasion I declared the principles on which I believed it my duty to administer the affairs of our Commonwealth. MY conscience tells me I have on every occasion acted up to that declaration according to its obvious import and to the understanding of every candid mind.

In the transaction of your foreign affairs we have endeavored to cultivate the friendship of all nations, and especially of those with which we have the most important relations. We have done them justice on all occasions, favored where favor was lawful, and cherished mutual interests and intercourse on fair and equal terms. We ar

List all text files in the corpus

In [71]:
data=[]
path='C:\\Users\\Lamia\\AppData\\Roaming\\nltk_data\\corpora\\inaugural'
path=os.path.join(path, '*.txt')
#path
files = glob(path)
#print (files)
for f in files:
    with open(f) as document:
        data.append(document.read())
        

In [72]:
len(data) #58 text files
data[2]

"When it was first perceived, in early times, that no middle course for America remained between unlimited submission to a foreign legislature and a total independence of its claims, men of reflection were less apprehensive of danger from the formidable power of fleets and armies they must determine to resist than from those contests and dissensions which would certainly arise concerning the forms of government to be instituted over the whole and over the parts of this extensive country. Relying, however, on the purity of their intentions, the justice of their cause, and the integrity and intelligence of the people, under an overruling Providence which had so signally protected this country from the first, the representatives of this nation, then consisting of little more than half its present number, not only broke to pieces the chains which were forging and the rod of iron that was lifted up, but frankly cut asunder the ties which had bound them, and launched into an ocean of uncerta

Preprocessing, cleaning and stemming

In [73]:

REPLACE_NO_SPACE = re.compile("(\.)|(\;)|(\:)|(\!)|(\')|(\?)|(\,)|(\")|(\()|(\))|(\[)|(\])")
REPLACE_WITH_SPACE = re.compile("(\n\s*)|(\-)|(\--)|(\/)")

def review_to_words(document):
    words = REPLACE_NO_SPACE.sub("", document.lower())
    words = REPLACE_WITH_SPACE.sub(" ", words)
    return words

In [74]:
clean_docs = [review_to_words(document) for document in data]
clean_docs[1]

'fellow citizens i am again called upon by the voice of my country to execute the functions of its chief magistrate when the occasion proper for it shall arrive i shall endeavor to express the high sense i entertain of this distinguished honor and of the confidence which has been reposed in me by the people of united america previous to the execution of any official act of the president the constitution requires an oath of office this oath i am now about to take and in your presence that if it shall be found during my administration of the government i have in any instance violated willingly or knowingly the injunctions thereof i may besides incurring constitutional punishment be subject to the upbraidings of all who are now witnesses of the present solemn ceremony '

LEt's start stemming all docs


In [75]:
porter = nltk.PorterStemmer()
porter.stem(clean_docs[1])

'fellow citizens i am again called upon by the voice of my country to execute the functions of its chief magistrate when the occasion proper for it shall arrive i shall endeavor to express the high sense i entertain of this distinguished honor and of the confidence which has been reposed in me by the people of united america previous to the execution of any official act of the president the constitution requires an oath of office this oath i am now about to take and in your presence that if it shall be found during my administration of the government i have in any instance violated willingly or knowingly the injunctions thereof i may besides incurring constitutional punishment be subject to the upbraidings of all who are now witnesses of the present solemn ceremony '

See? this isn't working since the stemmer considers the whole sentence as one word...

In [76]:

def stem_corpus(corpus_list):
    Clean_stem_docs=[]    
    porter = nltk.PorterStemmer() #constructor.
    #tokenize each document words and put put each doc in stemmed_doc list then remove it to corpus list named Clean_stem_docs
    for i in range (len(corpus_list)):
        stemmed_doc=[]
        token_words=word_tokenize(corpus_list[i])
        for word in token_words:
            stemmed_doc.append(porter.stem(word))
        stemmed_doc=" ".join(stemmed_doc)
        Clean_stem_docs.append(stemmed_doc)
    return Clean_stem_docs


clean_stemmed_docs=stem_corpus(clean_docs)


In [77]:
clean_stemmed_docs
#clean_stemmed_docs[1]

['fellow citizen of the senat and of the hous of repres among the vicissitud incid to life no event could have fill me with greater anxieti than that of which the notif wa transmit by your order and receiv on the 14th day of the present month on the one hand i wa summon by my countri whose voic i can never hear but with vener and love from a retreat which i had chosen with the fondest predilect and in my flatter hope with an immut decis as the asylum of my declin year a retreat which wa render everi day more necessari as well as more dear to me by the addit of habit to inclin and of frequent interrupt in my health to the gradual wast commit on it by time on the other hand the magnitud and difficulti of the trust to which the voic of my countri call me be suffici to awaken in the wisest and most experienc of her citizen a distrust scrutini into hi qualif could not but overwhelm with despond one who inherit inferior endow from natur and unpract in the duti of civil administr ought to be 

In [78]:
vocabulary_size=5000
vectorizer = CountVectorizer(max_features=vocabulary_size) #constructor.
features = vectorizer.fit_transform(clean_stemmed_docs)
#features
#print(features[0])
#print(vectorizer.get_feature_names())
Arr_features=features.toarray()
#len(Arr_features[1]) #definitely=5000
print(Arr_features)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [79]:
for i in range(0,5000):
    if Arr_features[0][i]>1:
        print (Arr_features[0][i])

2
2
2
2
3
2
10
48
3
2
14
2
2
2
27
7
3
2
3
20
2
9
3
2
3
5
2
2
2
2
3
5
2
2
2
2
3
3
5
2
3
2
9
4
2
2
3
3
2
12
2
2
7
2
2
3
9
3
5
4
3
13
2
2
5
2
2
2
2
2
2
2
2
31
2
2
3
7
15
2
2
3
3
2
2
6
8
3
2
8
3
3
22
4
4
3
2
2
8
2
4
3
71
2
15
4
2
5
2
4
2
2
2
2
2
4
2
2
2
5
2
2
2
6
2
3
2
2
2
2
2
2
2
2
3
2
4
3
3
2
2
2
2
3
2
2
2
2
6
18
116
3
2
2
3
3
3
10
3
48
3
2
2
5
2
4
2
2
4
2
36
3
2
10
17
2
5
9


# tf-idf

In [80]:
#clean_stemmed_docs
vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform(clean_stemmed_docs)
#vectors
#print(vectorizer.get_feature_names())
Arr_features =vectors.toarray()
Arr_features

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [81]:
for i in range(0,5000):
    if Arr_features[0][i]<1 and Arr_features[0][i]>0:
        print (Arr_features[0][i])

0.023269153181395264
0.009656268397788381
0.021117239427467696
0.01223299060033426
0.023269153181395264
0.007783749274570092
0.014727427862491874
0.019590432321041594
0.0116078839528328
0.014221590781300853
0.013334989258142048
0.016157347217311376
0.010081076846406698
0.021117239427467696
0.021117239427467696
0.015567498549140184
0.020613904621799514
0.009455970198905235
0.020613904621799514
0.019590432321041594
0.008896793248210641
0.006986160694824447
0.014221590781300853
0.008722768728441561
0.01592181702614105
0.019590432321041594
0.009656268397788381
0.012941678067205411
0.01662039892755908
0.007783749274570092
0.012804711972106059
0.006864149060593517
0.05397997155417795
0.2547490724182568
0.0060806046074396046
0.01662039892755908
0.00823251836136717
0.012941678067205411
0.012575514108564308
0.014221590781300853
0.014727427862491874
0.014727427862491874
0.01592181702614105
0.012575514108564308
0.028443181562601706
0.07557196017584913
0.0116078839528328
0.019590432321041594
0.019